### ISSUE TITLE
Output may fail to run on virtualized assemblies.

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [HoLLy-HaCKeR/EazFixer#13]
Virtualized assemblies can have virtualized code that references the string decryptor (or other normally removed code). Once these types get removed, the virtualized code will fail to run since it cannot resolve it anymore. Related, it could be that we're changing MDTokens when we save the assembly, we shouldn't do that by default (see de4dot's --keep-tokens).

It should be easy to fix this by adding a commandline flag similar to de4dot's --keep-types.

See #12.

**Comment by CreateAndInject** [comment]
What is virtualized? Does de4dot devirtualize  methods for old Eazfusctor version?

**Comment by HoLLy-HaCKeR** [comment]
To make virtualized methods, EazFuscator creates a virtual machine that executed IL or IL-like instructions and will use that to run the method. You can find more on their documentation [here](https://www.gapotchenko.com/eazfuscator.net/features/virtualization). As far as I know, de4dot does not devirtualize EazFuscator. However, there is [eazdevirt by Saneki](https://github.com/saneki/eazdevirt) or [my fork of it](https://github.com/HoLLy-HaCKeR/eazdevirt), although both are outdated by now.

**Comment by DevSecurity** [comment]
Any hopes for devirtualization?

**Comment by HoLLy-HaCKeR** [comment]
Devirtualization is a very large beast to tackle. It takes a very long time to implement in the first place, and keeping it updated is a very boring job I wouldn't wish on anyone. There is a good reason why it is the most secure protection EazFuscator has to offer. To give you an idea on how annoying updating devirtualizers is: I've already turned down hundreds of dollars just so I wouldn't have to do it.

For now, I have no plans to add devirtualization to EazFixer, and I don't think I will accept PRs adding the functionality because then I will be burdened with keeping it updated. Perhaps in the future I will make one, but I wouldn't count on it.

**Comment by DevinoPro** [comment]
Hi

**Comment by squirr3l-ex** [comment]
@DevinoPro virtual opcodes are in a giant list, EazFuscator itself is not a great obfuscator its just boring to make a tool, if you want a dirty method but doesnt support code you cannot execute just attach a debugger to the the program and step through method stubs and look what it invokes.

**Comment by HoLLy-HaCKeR** [comment]
Fixed since #15, you can now use `--fix-virt` or `--keep-types`.
