### ISSUE TITLE
Another weird case

### ISSUE THREAD

**Issue by piratesephiroth** [HoLLy-HaCKeR/EazFixer#14]
This one seems to be protected with a recent version of the obfuscator.
de4dot can decrypt some of the strings but no resources or embedded assemblies at all.
EazFixer can decrypt most strings but that's it because only the StringFixer displays "Success".

I tried your fork of eazdevirt and it doesn't seem to find any traces of virtualizationr.

[c.zip](https://github.com/HoLLy-HaCKeR/EazFixer/files/2348582/c.zip)

**Comment by squirr3l-ex** [comment]
try the new update with --keep-types

EazFixer.exe  --file Connectify.exe --virt-fix

The assembly itself does not have much virtualized you could try making whatever changes you are aiming for without devirting by patching unvirtualized CIL code.

**Comment by piratesephiroth** [comment]
Yeah it is possible to patch it as it is.

The new command line switches in the update didn't really improve the result though.

**Comment by HoLLy-HaCKeR** [comment]
I assume you did deobfuscate the control flow with de4dot? Try that first, making sure to keep the mdtokens the same.

**Comment by piratesephiroth** [comment]
Yes. Results are the basically same even after control flow deobfuscation.
`--keep-types` only applies the string fixer, similar to when I use no command switches at all
`--virt-fix` fails to apply alll the patches and the string fixer error says "Cleanup error: VirtFix enabled, Cannot remove method"

**Comment by HoLLy-HaCKeR** [comment]
I'll take a look at the sample.

**Comment by HoLLy-HaCKeR** [comment]
Please try the latest master, I fixed multiple issues and it now works on my end.
