### ISSUE TITLE
error prompt

### ISSUE THREAD

**Issue by lxa520** [HoLLy-HaCKeR/EazFixer#20]
Applied patches:
StringFixer: Failed (Init error: Could not find decrypter method)
ResourceResolver: Failed (Init error: Could not find resolver type)
AssemblyResolver: Failed (StringFixer is required!)

**Comment by HoLLy-HaCKeR** [comment]
Your assembly is not obfuscated by EazFuscator.

**Comment by lxa520** [comment]
I use "Exeinfo PE" software, 

The contents are as follows: 

image is 32bit executable:
Eazfuscator.NET v3.3 - 5.0 [ v3.x ] - (C) 2008-2015 Gapotchenko  - http://www.gapotchenko.com/eazfuscator.net - EP Token : 06000253

Lamer Info - Help Hint -Unpack info: 
.NET obf/license protector - for ver. < 5.0 - Unpack with : de4dot v3.1  2011-2014 de4dot@gmail.com - http://github.com/0xd4d/de4dot

**Comment by lxa520** [comment]
i use Eazfuscator.NET v3.3 obfuscate my assembly

then use eazfixer deobfuscated it, The result is the same as above.

**Comment by HoLLy-HaCKeR** [comment]
That is an older version of EazFuscator. Use de4dot. If that doesn't work, try making your own version of this tool.

**Comment by lxa520** [comment]
thank u
I'm not obfuscate project, I'm obfuscate assembly. the eazfuscator don`t deobfuscate assembly.
i use de4dot , the string deobfuscate results  as follow GForm GClass.
