### ISSUE TITLE
Method Was Removed that is still referenced by this module

### ISSUE THREAD

**Issue by pepsipu** [HoLLy-HaCKeR/EazFixer#21]
https://gyazo.com/63d065da67bca62356680c4301e94d56
I'm not sure what causes this bug, but the methods are defined.

**Comment by HoLLy-HaCKeR** [comment]
You can try using the `--keep-types` flag for now, as a workaround. If you upload your sample, I can take a look at it at some point in the future.

**Comment by sunriseiscool** [comment]
> 
> 
> You can try using the `--keep-types` flag for now, as a workaround. If you upload your sample, I can take a look at it at some point in the future.

https://info.snipr.gg/

here's a link to it

**Comment by HoLLy-HaCKeR** [comment]
Closing as stale
