### ISSUE TITLE
Deofuscation .dll instead of .exe

### ISSUE THREAD

**Issue by GKhelio** [HoLLy-HaCKeR/EazFixer#22]
Good, I try to pass the program an obfuscated dll, but it does not work, it is contemplated the defocusing of dll.

**Comment by sasha2002** [comment]
@HoLLy-HaCKeR  any news about dll?

**Comment by HoLLy-HaCKeR** [comment]
I'll try to look into it later.

**Comment by HoLLy-HaCKeR** [comment]
@sasha2002 Please upload your broken sample, my test one works fine.

**Comment by sasha2002** [comment]
@HoLLy-HaCKeR https://anonfile.com/f4Q3Jcr1o6/MyDLL_rar
As i can see they somehow obfuscate not all strings and methods, is like selective.

**Comment by HoLLy-HaCKeR** [comment]
@sasha2002 Please upload it to a proper filehost that doesn't error out when I try to download it, or directly as a github attachement.

**Comment by sasha2002** [comment]
https://www.upload.ee/files/11532632/MyDLL.zip.html
[MyDLL.zip](https://github.com/HoLLy-HaCKeR/EazFixer/files/4511418/MyDLL.zip)

**Comment by HoLLy-HaCKeR** [comment]
That assembly only has virtualization, which is not supported by EazFixer. Since I don't have any samples of supported obfuscation techniques that do not work in .dll files, I will close this issue.
