### ISSUE TITLE
sample packed exe for eazdevirt

### ISSUE THREAD

**Issue by ewwink** [HoLLy-HaCKeR/EazFixer#23]
Hi,
I see you made improvement for eazdevirt https://github.com/HoLLy-HaCKeR/eazdevirt now I want to try to make it compatible with latest eaz, do you have sample unpackme that compatible with your modified eazdevirt?

**Comment by HoLLy-HaCKeR** [comment]
I've used this on the game [osu!](https://osu.ppy.sh/home). I'm not sure about the exact update.

**Comment by ewwink** [comment]
it produce error maybe it not use same version of eaz but thanks.

**Comment by ewwink** [comment]
sorry to ask again about eazdevirt, do you know how to identify instruction type from dictionary?
for example `this.method_50` is instruction for `Stfld (Is_Stfld)` but how do I now about it?
```C#
private Dictionary<int, Class71.Class75> method_219()
{
  return new Dictionary<int, Class71.Class75>(256)
  {
    {
      this.class34_0.class67_186.method_1(),
      new Class71.Class75(this.class34_0.class67_186, new Class71.Delegate1(this.method_50))
    },
```

**Comment by HoLLy-HaCKeR** [comment]
Doesn't ring a bell. I suggest you start renaming symbol names in your effort to reverse engineer it.

**Comment by ewwink** [comment]
can you look [this thread](https://forum.tuts4you.com/topic/41350-e) and thanks.

**Comment by HoLLy-HaCKeR** [comment]
No, this is a GitHub issue, not a support forum.
