### ISSUE TITLE
String DeObfuscation

### ISSUE THREAD

**Issue by HeroinGyrl** [HoLLy-HaCKeR/EazFixer#26]
In Eazfsucator 2019.1 String decryption does not works.

I'm getting that error:

> Executing memory patches ...
Wrong MethodAttributes or CallingConventions for DynamicMethod. Only "public", "static" and "standard" are supported

**Comment by Azukee** [comment]
Can you please attach some kind of file that doesn't work?
Eaz 2019.4 seems to work fine with EazFixer.

**Comment by HeroinGyrl** [comment]
In Eazfuscator 2019.1
Just made a console application and use `string test = "testing strings";`

**Comment by Azukee** [comment]
![image](https://user-images.githubusercontent.com/10087856/71772924-4fc09180-2f54-11ea-9f09-651fcafd97d0.png)
Can't seem to re-create, eazfixer runs through the program just fine.

**Comment by HoLLy-HaCKeR** [comment]
@HeroinGyrl please make sure you are using the latest master. If that does not work, please post a stacktrace of the exception (may require removing some try/catch blocks) and post your OS info.

**Comment by HeroinGyrl** [comment]
Ah okay. the problem was not by eazfixer. the Harmony Lib was outdated. works now.
