### ISSUE TITLE
Unfortunetly doesnt work for Eazfuscator.NET 2019.4

### ISSUE THREAD

**Issue by sinask** [HoLLy-HaCKeR/EazFixer#28]
unfortunately doesn't work for this .this program apparently obfuscating with latest version

[License.zip](https://github.com/HoLLy-HaCKeR/EazFixer/files/4272736/License.zip)

**Comment by CreateAndInject** [comment]
Just enable loadFromRemoteSources.

@HoLLy-HaCKeR Do you have the installer of Eazfuscator 5.2? I need it.

**Comment by sinask** [comment]
where ?how can i enable it?

**Comment by sinask** [comment]
> Just enable loadFromRemoteSources.

where ?how can i enable it?

**Comment by CreateAndInject** [comment]
This file is protected by code virtualization which isn't supported.
By the way, how do you know it's version 2019.4?

@HoLLy-HaCKeR Eazfuscator usually renames symbols like `\u0002\u0003`
But sometimes the symbol starts with `#=`, such as `#=zs0VMZl4=`.
Is there any option in Eazfuscator which can control how to rename? Or that file is obfuscated by multi obfuscators?

**Comment by HoLLy-HaCKeR** [comment]
Symbol names that start with #=z are encrypted by Eazfuscator, meaning they can be decrypted again if you have the key. If the names are changed to random characters (such as \u0002\u0003), they are wiped and cannot be recovered.

Closing this as virtualized code is out of scope. Try your luck with Eazdevirt.
