### ISSUE TITLE
unpacked problem

### ISSUE THREAD

**Issue by Anonymous-ghost** [HoLLy-HaCKeR/EazFixer#39]
Executing memory patches...
Initializing modules...
Processing...
Cleanup...

Applied patches:
StringFixer: Success
ResourceResolver: Failed (Init error: Could not find resolver type)
AssemblyResolver: Failed (值不能为 null。
参数名: source)

Writing new assembly...
Done.
![ok](https://user-images.githubusercontent.com/42628190/94339597-96e43a80-002d-11eb-834c-27d4c1985e80.jpg)

**Comment by HoLLy-HaCKeR** [comment]
Please follow the bug report template.
