### ISSUE TITLE
ResourceResolver and AssemblyResolver Failed (Init error: Could not find resolver type)

### ISSUE THREAD

**Issue by Aholicknight** [HoLLy-HaCKeR/EazFixer#47]
![exeinfope_6345341274](https://user-images.githubusercontent.com/7843719/190712124-238f2456-cf19-4fb1-b063-a76dabd9fa68.png)
This program is protected with Eazfuscator.NET v2020.x - 2021.3 and I am trying to deobfuscate the program. 

I first use String Decryptor 2.0 to decrypt strings, and the program decrypted 123 strings + 2 methods 
![image](https://user-images.githubusercontent.com/7843719/190712488-47ee23e4-e78c-4e90-81a3-aa82e0a208f4.png)

Then I use `EazFixer.exe --file` and this is the output:
```
Executing memory patches...
Initializing modules...
Processing...
Cleanup...

Applied patches:
StringFixer: Success
ResourceResolver: Failed (Init error: Could not find resolver type)
AssemblyResolver: Failed (Init error: Could not find resolver type)

Writing new assembly...
Done.
```

Am I doing something wrong? Thank you for your support.

**Comment by HoLLy-HaCKeR** [comment]
If the resolver types could not be found, it most likely means that assembly merging and resource encryption were not used. Everything is working as intended, and you're doing nothing wrong :)

I should probably update the tool at some point to not print this as a red error since it's not an actual failure.

**Comment by Aholicknight** [comment]
> If the resolver types could not be found, it most likely means that assembly merging and resource encryption were not used. Everything is working as intended, and you're doing nothing wrong :)
> 
> I should probably update the tool at some point to not print this as a red error since it's not an actual failure.

Sounds good. When opening the unpacked file from EazFixer it shows this error: 
![dopus_4847789808](https://user-images.githubusercontent.com/7843719/190716800-d84636ba-5471-4933-9839-3ef1ec515cbe.png)

**Comment by HoLLy-HaCKeR** [comment]
Try `--keep-types` or `--virt-fix` flags. Test without running de4dot as it can break virtualized code.

**Comment by Aholicknight** [comment]
> Try `--keep-types` or `--virt-fix` flags. Do not use de4dot renaming as it can break virtualized code.

Will try this. What is the command for de4dot to prevent renaming? Thank you

**Comment by HoLLy-HaCKeR** [comment]
Look at the de4dot help file.

**Comment by Aholicknight** [comment]
> Look at the de4dot help file.

Figured out which one to use and the program now runs in dnSpy without the error. The only problem left is all the classes are named "\u0002\u2007" and so forth. 

![ZYAJV5HEQm](https://user-images.githubusercontent.com/7843719/190834946-3e1e66f6-034a-455f-8861-3b4db91d3c74.png)

At least I can see the strings so hopefully this will be easier
