### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by gokaybiz** [holly-hacker/EazFixer#48]
I'm getting error given below:
```
Could not load file or assembly 'xxxxx, Version=1.0 Culture=neutral, PublicKeyToken=null' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
```
**Checklist**:
- [X] I have checked that I am dealing with an EazFuscator binary, and believe that it can't be another obfuscator such as ConfuserEx.
- [-] I understand that an error message may mean that a certain protection was not present.
- [X] I can share a sample that can reproduce the bug

**Comment by holly-hacker** [comment]
Your executable is not a valid .NET binary (likely if you dumped it incorrectly), or there is a bug in dnlib meaning it cannot load your executable correctly. In either case, this is not an EazFixer bug.

**Comment by gokaybiz** [comment]
![die](https://i.imgur.com/L8wKyyx.png)
But DiE says it is. Can it be copycat?

**Comment by holly-hacker** [comment]
It looks like the executable has some modifications made to it that differ from standard EazFuscator, making it so it can't be loaded with reflection. This isn't something you can fix without patching the executable itself. You can try running it through de4dot but I cannot guarantee that EazFixer will ever work on this executable.

**Comment by gokaybiz** [comment]
de4dot also couldn't decompile methods, procedures etc.
What's more, when I try to debug with ollydbg the executable closes itself.

Do you have any extra tricks to decompile and "patch" my silly software?

**Comment by holly-hacker** [comment]
No. There is more to this executable than just standard EazFuscator so it's out of scope for this project, and this issue thread is not a support forum. I suggest going to a forum dedicated to reverse engineering and asking for help there.
