### ISSUE TITLE
how to solved?

### ISSUE THREAD

**Issue by billpeace** [holly-hacker/EazFixer#49]
<html>
<body>

// this can fail

Type type = ass.GetType(meth.DeclaringType.ReflectionFullName);
 return type?.GetMethod(meth.Name, flags, null, args, null);

</body>
</html>

how to?

thanks 

how to remove bug labels?

**Comment by holly-hacker** [comment]
I don't understand what you are asking. If the code you mentioned failed, then there is probably an issue with a renamed name that EazFixer doesn't detect. If that's the case, please open an issue with more information that allows me to reproduce the issue.
