### ISSUE TITLE
Support for 2018.2

### ISSUE THREAD

**Issue by developer-variety** [HoLLy-HaCKeR/EazFixer#5]
I have test deobfuscation with EazFixer and de4dot.

**Comment by HoLLy-HaCKeR** [comment]
Some more info? What exactly is broken? I'll take a look at it tomorrow.

**Comment by HoLLy-HaCKeR** [comment]
Also, can you upload your sample? My target either hasn't update to Eazfuscator 2018.2, or no update is needed and your sample isn't using Eazfuscator.

**Comment by developer-variety** [comment]
Yes absolutely.

Nothing really seemed to work on this sample. String encryption didn't work (but said it did), and the other features failed.


[ObfuscatorTests.zip](https://github.com/HoLLy-HaCKeR/EazFixer/files/1997557/ObfuscatorTests.zip)

**Comment by developer-variety** [comment]
I have just tried again, and it string encryption seemed to work. :thinking:

**Comment by HoLLy-HaCKeR** [comment]
Yeah, it works for me too. I don't see a reason why it wouldn't work, unless the ldc.i instruction isn't directly in front of the call to the string decrypter (but that doesn't seem to be the case).

I'll be closing this then. If you have any other samples that don't work, create a new issue and upload them there.
