### ISSUE TITLE
The name 'asmEnumerator' does not exist in the current context	

### ISSUE THREAD

**Issue by NotKeCa** [HoLLy-HaCKeR/EazFixer#8]
The error is on Line 67 in AssemblyResolver.cs

**Comment by HoLLy-HaCKeR** [comment]
Oh what, the guy that submitted the previous PR didn't even bother to compile his own code. Give me a sec, I'll fix this.

**Comment by HoLLy-HaCKeR** [comment]
I've undone the commit that caused this, as I'm not sure his patches are even working.
